# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  socket: /tmp/mysql.sock
  adapter: mysql
  database: celulaz_production
  username: root
  password:
  host: localhost
  reconnect: true

profiling:
  socket: /tmp/mysql.sock
  encoding: utf8
  adapter: mysql
  database: autonomoz_production
  username: root
  password: 
  host: localhost
  reconnect: true

test:
  adapter: mysql
  socket: /tmp/mysql.sock
  encoding: utf8
  database: proj_celulaz_test
  username: root
  password: 
  host: localhost
  reconnect: true

production:
  adapter: mysql
  database: autonomoz_production
  host: suaempreza.suaempreza.com.br
  username: bsiqueira
  password: suaempreza
  reconnect: true